### ISSUE TITLE
repex depends on mdtraj but setup.py does not automatically install mdtraj

### ISSUE THREAD

**Issue by jchodera** [choderalab/repex#128]
We need to make sure dependencies are automatically installed upon installation.

**Comment by kyleabeauchamp** [comment]
I'm going to close this as we're using conda to handle all dependencies.

**Comment by jchodera** [comment]
My thinking was that setup.py should still specify dependencies. That way,
a user trying to install from, say, github will have this fail if
dependencies are not present because pip cannot install all the
dependencies.
