### ISSUE TITLE
Have setuptools automagically specify dependencies via setup.py

### ISSUE THREAD

**Issue by jchodera** [choderalab/repex#36]
We should have any needed dependencies automatically installed.

**Comment by kyleabeauchamp** [comment]
I think we're using conda for this

**Comment by jchodera** [comment]
It can still be useful to have the dependencies specified in `setup.py` so that installation via `python setup.py install` will fail with a useful error message if dependencies are not satisfied.  We don't need to have the dependencies be `pip`-installable.

**Comment by kyleabeauchamp** [comment]
OK, we can reopen this.  

My goal is to find some way to avoid maintaining dependencies in three different locations (devtools/conda-recipe, omnia/conda-recipe, and setup.py).  Right now we haven't really been able to do this due to lack of time.

**Comment by kyleabeauchamp** [comment]
So here are two more reasons why I don't like using setup.py to do this stuff:

1.  The requirements are different for building, importing, and testing.  setup.py has no way for us to distinguish between these cases
2.  We have to *manually* write code to handle library versions, with library-specific code for each library

**Comment by jchodera** [comment]
Good point.

OK, let's omit all dependencies from `setup.py` for now and brainstorm a simple way to have `setup.py` talk to `conda` in the future.
